# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5cS_iVRJbgPtBHL2TR7Gj4LnCNCMAGL
"""

import torch
import torch.nn as nn

model = nn.Sequential(nn.Linear(2,4),nn.ReLU(),nn.Linear(4,1))

